// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(openac_mobile_appFFI)
import openac_mobile_appFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_openac_mobile_app_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_openac_mobile_app_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureOpenacMobileAppInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * Result of a complete benchmark run with timing and size metrics
 */
public struct BenchmarkResults {
    public var setupMs: UInt64
    public var proveMs: UInt64
    public var verifyMs: UInt64
    public var provingKeyBytes: UInt64
    public var verifyingKeyBytes: UInt64
    public var proofBytes: UInt64
    public var witnessBytes: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(setupMs: UInt64, proveMs: UInt64, verifyMs: UInt64, provingKeyBytes: UInt64, verifyingKeyBytes: UInt64, proofBytes: UInt64, witnessBytes: UInt64) {
        self.setupMs = setupMs
        self.proveMs = proveMs
        self.verifyMs = verifyMs
        self.provingKeyBytes = provingKeyBytes
        self.verifyingKeyBytes = verifyingKeyBytes
        self.proofBytes = proofBytes
        self.witnessBytes = witnessBytes
    }
}

#if compiler(>=6)
extension BenchmarkResults: Sendable {}
#endif


extension BenchmarkResults: Equatable, Hashable {
    public static func ==(lhs: BenchmarkResults, rhs: BenchmarkResults) -> Bool {
        if lhs.setupMs != rhs.setupMs {
            return false
        }
        if lhs.proveMs != rhs.proveMs {
            return false
        }
        if lhs.verifyMs != rhs.verifyMs {
            return false
        }
        if lhs.provingKeyBytes != rhs.provingKeyBytes {
            return false
        }
        if lhs.verifyingKeyBytes != rhs.verifyingKeyBytes {
            return false
        }
        if lhs.proofBytes != rhs.proofBytes {
            return false
        }
        if lhs.witnessBytes != rhs.witnessBytes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(setupMs)
        hasher.combine(proveMs)
        hasher.combine(verifyMs)
        hasher.combine(provingKeyBytes)
        hasher.combine(verifyingKeyBytes)
        hasher.combine(proofBytes)
        hasher.combine(witnessBytes)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBenchmarkResults: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BenchmarkResults {
        return
            try BenchmarkResults(
                setupMs: FfiConverterUInt64.read(from: &buf), 
                proveMs: FfiConverterUInt64.read(from: &buf), 
                verifyMs: FfiConverterUInt64.read(from: &buf), 
                provingKeyBytes: FfiConverterUInt64.read(from: &buf), 
                verifyingKeyBytes: FfiConverterUInt64.read(from: &buf), 
                proofBytes: FfiConverterUInt64.read(from: &buf), 
                witnessBytes: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: BenchmarkResults, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.setupMs, into: &buf)
        FfiConverterUInt64.write(value.proveMs, into: &buf)
        FfiConverterUInt64.write(value.verifyMs, into: &buf)
        FfiConverterUInt64.write(value.provingKeyBytes, into: &buf)
        FfiConverterUInt64.write(value.verifyingKeyBytes, into: &buf)
        FfiConverterUInt64.write(value.proofBytes, into: &buf)
        FfiConverterUInt64.write(value.witnessBytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBenchmarkResults_lift(_ buf: RustBuffer) throws -> BenchmarkResults {
    return try FfiConverterTypeBenchmarkResults.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBenchmarkResults_lower(_ value: BenchmarkResults) -> RustBuffer {
    return FfiConverterTypeBenchmarkResults.lower(value)
}


/**
 * Result of a proving operation with timing and proof metadata.
 * `prove_ms` is the total time for both circuits; `proof_size_bytes` is the combined size.
 */
public struct ProofResult {
    public var proveMs: UInt64
    public var proofSizeBytes: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(proveMs: UInt64, proofSizeBytes: UInt64) {
        self.proveMs = proveMs
        self.proofSizeBytes = proofSizeBytes
    }
}

#if compiler(>=6)
extension ProofResult: Sendable {}
#endif


extension ProofResult: Equatable, Hashable {
    public static func ==(lhs: ProofResult, rhs: ProofResult) -> Bool {
        if lhs.proveMs != rhs.proveMs {
            return false
        }
        if lhs.proofSizeBytes != rhs.proofSizeBytes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(proveMs)
        hasher.combine(proofSizeBytes)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProofResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProofResult {
        return
            try ProofResult(
                proveMs: FfiConverterUInt64.read(from: &buf), 
                proofSizeBytes: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: ProofResult, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.proveMs, into: &buf)
        FfiConverterUInt64.write(value.proofSizeBytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofResult_lift(_ buf: RustBuffer) throws -> ProofResult {
    return try FfiConverterTypeProofResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofResult_lower(_ value: ProofResult) -> RustBuffer {
    return FfiConverterTypeProofResult.lower(value)
}


/**
 * Circom-ready SMT inputs — all values as decimal strings, siblings padded to depth.
 * Mirrors `ecdsa_spartan2::smt_client::SmtCircuitInputs`.
 */
public struct SmtCircuitInputs {
    public var smtRoot: String
    public var serialNumber: String
    public var smtSiblings: [String]
    public var smtOldKey: String
    public var smtOldValue: String
    public var smtIsOld0: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(smtRoot: String, serialNumber: String, smtSiblings: [String], smtOldKey: String, smtOldValue: String, smtIsOld0: String) {
        self.smtRoot = smtRoot
        self.serialNumber = serialNumber
        self.smtSiblings = smtSiblings
        self.smtOldKey = smtOldKey
        self.smtOldValue = smtOldValue
        self.smtIsOld0 = smtIsOld0
    }
}

#if compiler(>=6)
extension SmtCircuitInputs: Sendable {}
#endif


extension SmtCircuitInputs: Equatable, Hashable {
    public static func ==(lhs: SmtCircuitInputs, rhs: SmtCircuitInputs) -> Bool {
        if lhs.smtRoot != rhs.smtRoot {
            return false
        }
        if lhs.serialNumber != rhs.serialNumber {
            return false
        }
        if lhs.smtSiblings != rhs.smtSiblings {
            return false
        }
        if lhs.smtOldKey != rhs.smtOldKey {
            return false
        }
        if lhs.smtOldValue != rhs.smtOldValue {
            return false
        }
        if lhs.smtIsOld0 != rhs.smtIsOld0 {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(smtRoot)
        hasher.combine(serialNumber)
        hasher.combine(smtSiblings)
        hasher.combine(smtOldKey)
        hasher.combine(smtOldValue)
        hasher.combine(smtIsOld0)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmtCircuitInputs: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmtCircuitInputs {
        return
            try SmtCircuitInputs(
                smtRoot: FfiConverterString.read(from: &buf), 
                serialNumber: FfiConverterString.read(from: &buf), 
                smtSiblings: FfiConverterSequenceString.read(from: &buf), 
                smtOldKey: FfiConverterString.read(from: &buf), 
                smtOldValue: FfiConverterString.read(from: &buf), 
                smtIsOld0: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SmtCircuitInputs, into buf: inout [UInt8]) {
        FfiConverterString.write(value.smtRoot, into: &buf)
        FfiConverterString.write(value.serialNumber, into: &buf)
        FfiConverterSequenceString.write(value.smtSiblings, into: &buf)
        FfiConverterString.write(value.smtOldKey, into: &buf)
        FfiConverterString.write(value.smtOldValue, into: &buf)
        FfiConverterString.write(value.smtIsOld0, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmtCircuitInputs_lift(_ buf: RustBuffer) throws -> SmtCircuitInputs {
    return try FfiConverterTypeSmtCircuitInputs.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmtCircuitInputs_lower(_ value: SmtCircuitInputs) -> RustBuffer {
    return FfiConverterTypeSmtCircuitInputs.lower(value)
}


/**
 * SMT proof from the moica-revocation-smt server, all values as hex strings.
 */
public struct SmtProof {
    /**
     * Tree root at proof time (hex string).
     */
    public var root: String
    /**
     * Sibling hashes from leaf level upward (hex strings).
     */
    public var siblings: [String]
    /**
     * [key] for non-membership; [key, value, marker] for membership.
     */
    public var entry: [String]
    /**
     * Present for non-membership proofs when a conflicting leaf exists.
     */
    public var matchingEntry: [String]?
    /**
     * True if the key is claimed to exist in the tree.
     */
    public var membership: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Tree root at proof time (hex string).
         */root: String, 
        /**
         * Sibling hashes from leaf level upward (hex strings).
         */siblings: [String], 
        /**
         * [key] for non-membership; [key, value, marker] for membership.
         */entry: [String], 
        /**
         * Present for non-membership proofs when a conflicting leaf exists.
         */matchingEntry: [String]?, 
        /**
         * True if the key is claimed to exist in the tree.
         */membership: Bool) {
        self.root = root
        self.siblings = siblings
        self.entry = entry
        self.matchingEntry = matchingEntry
        self.membership = membership
    }
}

#if compiler(>=6)
extension SmtProof: Sendable {}
#endif


extension SmtProof: Equatable, Hashable {
    public static func ==(lhs: SmtProof, rhs: SmtProof) -> Bool {
        if lhs.root != rhs.root {
            return false
        }
        if lhs.siblings != rhs.siblings {
            return false
        }
        if lhs.entry != rhs.entry {
            return false
        }
        if lhs.matchingEntry != rhs.matchingEntry {
            return false
        }
        if lhs.membership != rhs.membership {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(root)
        hasher.combine(siblings)
        hasher.combine(entry)
        hasher.combine(matchingEntry)
        hasher.combine(membership)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmtProof: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmtProof {
        return
            try SmtProof(
                root: FfiConverterString.read(from: &buf), 
                siblings: FfiConverterSequenceString.read(from: &buf), 
                entry: FfiConverterSequenceString.read(from: &buf), 
                matchingEntry: FfiConverterOptionSequenceString.read(from: &buf), 
                membership: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: SmtProof, into buf: inout [UInt8]) {
        FfiConverterString.write(value.root, into: &buf)
        FfiConverterSequenceString.write(value.siblings, into: &buf)
        FfiConverterSequenceString.write(value.entry, into: &buf)
        FfiConverterOptionSequenceString.write(value.matchingEntry, into: &buf)
        FfiConverterBool.write(value.membership, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmtProof_lift(_ buf: RustBuffer) throws -> SmtProof {
    return try FfiConverterTypeSmtProof.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmtProof_lower(_ value: SmtProof) -> RustBuffer {
    return FfiConverterTypeSmtProof.lower(value)
}


/**
 * Errors that can occur during ZK proof operations
 */
public enum ZkProofError {

    
    
    case FileNotFound(msg: String
    )
    case ProofGenerationFailed(msg: String
    )
    case VerificationFailed(msg: String
    )
    case InvalidInput(msg: String
    )
    case SetupRequired(msg: String
    )
    case IoError(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeZkProofError: FfiConverterRustBuffer {
    typealias SwiftType = ZkProofError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ZkProofError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .FileNotFound(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .ProofGenerationFailed(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .VerificationFailed(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .InvalidInput(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 5: return .SetupRequired(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 6: return .IoError(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ZkProofError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .FileNotFound(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .ProofGenerationFailed(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .VerificationFailed(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .InvalidInput(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .SetupRequired(msg):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .IoError(msg):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkProofError_lift(_ buf: RustBuffer) throws -> ZkProofError {
    return try FfiConverterTypeZkProofError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkProofError_lower(_ value: ZkProofError) -> RustBuffer {
    return FfiConverterTypeZkProofError.lower(value)
}


extension ZkProofError: Equatable, Hashable {}



extension ZkProofError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
/**
 * Parse a @zk-kit/smt v1.0.2-compatible snapshot JSON and return its root.
 *
 * The returned root can be used as `expected_root` in subsequent calls to
 * `verify_smt_proof`.
 */
public func buildSmtFromSnapshot(snapshotJson: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_openac_mobile_app_fn_func_build_smt_from_snapshot(
        FfiConverterString.lower(snapshotJson),$0
    )
})
}
/**
 * Load a snapshot and generate a proof for `key_hex` in one call (JSON input).
 *
 * # Arguments
 * * `snapshot_json` – decompressed snapshot JSON string
 * * `key_hex`       – certificate serial number as a hex string (with or without `0x`)
 *
 * Returns the proof ready to pass straight into `verify_smt_proof`.
 */
public func createSmtProof(snapshotJson: String, keyHex: String)throws  -> SmtProof  {
    return try  FfiConverterTypeSmtProof_lift(try rustCallWithError(FfiConverterTypeZkProofError_lift) {
    uniffi_openac_mobile_app_fn_func_create_smt_proof(
        FfiConverterString.lower(snapshotJson),
        FfiConverterString.lower(keyHex),$0
    )
})
}
/**
 * Load a snapshot and generate a proof for `key_hex` in one call (gzip input).
 *
 * # Arguments
 * * `gz_data` – raw bytes of the `.json.gz` snapshot file
 * * `key_hex` – certificate serial number as a hex string (with or without `0x`)
 *
 * Returns the proof ready to pass straight into `verify_smt_proof`.
 */
public func createSmtProofFromGz(gzData: Data, keyHex: String)throws  -> SmtProof  {
    return try  FfiConverterTypeSmtProof_lift(try rustCallWithError(FfiConverterTypeZkProofError_lift) {
    uniffi_openac_mobile_app_fn_func_create_smt_proof_from_gz(
        FfiConverterData.lower(gzData),
        FfiConverterString.lower(keyHex),$0
    )
})
}
/**
 * Generate split circuit inputs for both cert_chain_rs4096 and device_sig_rs2048.
 *
 * Writes two JSON files into `output_dir`:
 * - `cert_chain_rs4096_input.json`
 * - `device_sig_rs2048_input.json`
 *
 * These are the input files expected by `prove` via `PathConfig::mobile`.
 *
 * `smt_proof` should be the non-membership proof for the certificate's serial
 * number, produced by `create_smt_proof_from_gz` / `create_smt_proof`.
 * Pass `None` to omit SMT revocation checking.
 */
public func generateCertChainRs4096Input(certb64: String, signedResponse: String, tbs: String, issuerCertPath: String, smtSnapshotPath: String?, outputDir: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeZkProofError_lift) {
    uniffi_openac_mobile_app_fn_func_generate_cert_chain_rs4096_input(
        FfiConverterString.lower(certb64),
        FfiConverterString.lower(signedResponse),
        FfiConverterString.lower(tbs),
        FfiConverterString.lower(issuerCertPath),
        FfiConverterOptionString.lower(smtSnapshotPath),
        FfiConverterString.lower(outputDir),$0
    )
})
}
/**
 * Verify proofs for cert_chain_rs4096 and device_sig_rs2048 circuits.
 */
public func linkVerify(documentsPath: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeZkProofError_lift) {
    uniffi_openac_mobile_app_fn_func_link_verify(
        FfiConverterString.lower(documentsPath),$0
    )
})
}
/**
 * Test function for basic UniFFI integration
 */
public func moproHelloWorld() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_openac_mobile_app_fn_func_mopro_hello_world($0
    )
})
}
/**
 * Generate proofs for cert_chain_rs4096 circuit.
 *
 * Reads input JSONs via `PathConfig::mobile(documents_path)`:
 * - `{documents_path}/cert_chain_rs4096_input.json`
 *
 * Writes proofs, instances, and witnesses under `{documents_path}/keys/`.
 *
 * Witnesses are pre-warmed before any Spartan2 key I/O so that witnesscalc's
 * C++ realloc runs on a clean heap and avoids macOS SIGSEGV from moved pointers.
 */
public func proveCertChainRs4096(documentsPath: String)throws  -> ProofResult  {
    return try  FfiConverterTypeProofResult_lift(try rustCallWithError(FfiConverterTypeZkProofError_lift) {
    uniffi_openac_mobile_app_fn_func_prove_cert_chain_rs4096(
        FfiConverterString.lower(documentsPath),$0
    )
})
}
/**
 * Generate proofs for both cert_chain_rs4096 and device_sig_rs2048 circuits.
 *
 * Reads input JSONs via `PathConfig::mobile(documents_path)`:
 * - `{documents_path}/cert_chain_rs4096_input.json`
 * - `{documents_path}/device_sig_rs2048_input.json`
 *
 * Writes proofs, instances, and witnesses under `{documents_path}/keys/`.
 *
 * Witnesses are pre-warmed before any Spartan2 key I/O so that witnesscalc's
 * C++ realloc runs on a clean heap and avoids macOS SIGSEGV from moved pointers.
 */
public func proveDeviceSigRs2048(documentsPath: String)throws  -> ProofResult  {
    return try  FfiConverterTypeProofResult_lift(try rustCallWithError(FfiConverterTypeZkProofError_lift) {
    uniffi_openac_mobile_app_fn_func_prove_device_sig_rs2048(
        FfiConverterString.lower(documentsPath),$0
    )
})
}
/**
 * Run complete benchmark pipeline for both cert_chain_rs4096 and device_sig_rs2048 circuits.
 *
 * Witnesses are pre-warmed on a clean heap before Spartan2 setup to prevent macOS SIGSEGV:
 * witnesscalc's C++ `realloc()` moves large allocations on a fragmented heap, leaving stale
 * interior pointers. Pre-warming ensures the realloc happens before heap fragmentation.
 * Each circuit is then processed in isolation (setup → save → drop PK → prove → verify) to
 * avoid holding two large proving keys in memory simultaneously. Timings and sizes are combined.
 */
public func runCompleteBenchmark(documentsPath: String)throws  -> BenchmarkResults  {
    return try  FfiConverterTypeBenchmarkResults_lift(try rustCallWithError(FfiConverterTypeZkProofError_lift) {
    uniffi_openac_mobile_app_fn_func_run_complete_benchmark(
        FfiConverterString.lower(documentsPath),$0
    )
})
}
/**
 * Setup circuit keys for both cert_chain_rs4096 and device_sig_rs2048.
 *
 * Requires that `{documents_path}/cert_chain_rs4096.r1cs` and
 * `{documents_path}/device_sig_rs2048.r1cs` are present.
 */
public func setupKeys(documentsPath: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeZkProofError_lift) {
    uniffi_openac_mobile_app_fn_func_setup_keys(
        FfiConverterString.lower(documentsPath),$0
    )
})
}
/**
 * Convert an `SmtProof` (hex strings) into the `SmtCircuitInputs` that the
 * Circom cert-chain circuit expects (decimal strings, siblings padded to `depth`).
 *
 * This is the offline equivalent of `ecdsa_spartan2::smt_client::fetch_smt_proof`:
 * instead of hitting the server you supply the proof generated from the local snapshot.
 */
public func smtProofToCircuitInputs(proof: SmtProof, depth: UInt32)throws  -> SmtCircuitInputs  {
    return try  FfiConverterTypeSmtCircuitInputs_lift(try rustCallWithError(FfiConverterTypeZkProofError_lift) {
    uniffi_openac_mobile_app_fn_func_smt_proof_to_circuit_inputs(
        FfiConverterTypeSmtProof_lower(proof),
        FfiConverterUInt32.lower(depth),$0
    )
})
}
/**
 * Verify proofs for cert_chain_rs4096 circuit.
 */
public func verifyCertChainRs4096(documentsPath: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeZkProofError_lift) {
    uniffi_openac_mobile_app_fn_func_verify_cert_chain_rs4096(
        FfiConverterString.lower(documentsPath),$0
    )
})
}
/**
 * Verify proofs for device_sig_rs2048 circuit.
 */
public func verifyDeviceSigRs2048(documentsPath: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeZkProofError_lift) {
    uniffi_openac_mobile_app_fn_func_verify_device_sig_rs2048(
        FfiConverterString.lower(documentsPath),$0
    )
})
}
/**
 * Verify an SMT non-membership (or membership) proof against a trusted root.
 *
 * Recomputes the Merkle root from `proof.entry` + `proof.siblings` using
 * Poseidon-P256, then compares against `expected_root`.  Returns `true` iff
 * the proof is valid.
 */
public func verifySmtProof(proof: SmtProof, expectedRoot: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_openac_mobile_app_fn_func_verify_smt_proof(
        FfiConverterTypeSmtProof_lower(proof),
        FfiConverterString.lower(expectedRoot),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_openac_mobile_app_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_openac_mobile_app_checksum_func_build_smt_from_snapshot() != 37072) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openac_mobile_app_checksum_func_create_smt_proof() != 25623) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openac_mobile_app_checksum_func_create_smt_proof_from_gz() != 33213) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openac_mobile_app_checksum_func_generate_cert_chain_rs4096_input() != 14364) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openac_mobile_app_checksum_func_link_verify() != 4694) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openac_mobile_app_checksum_func_mopro_hello_world() != 46672) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openac_mobile_app_checksum_func_prove_cert_chain_rs4096() != 42180) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openac_mobile_app_checksum_func_prove_device_sig_rs2048() != 31190) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openac_mobile_app_checksum_func_run_complete_benchmark() != 7344) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openac_mobile_app_checksum_func_setup_keys() != 1011) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openac_mobile_app_checksum_func_smt_proof_to_circuit_inputs() != 957) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openac_mobile_app_checksum_func_verify_cert_chain_rs4096() != 13705) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openac_mobile_app_checksum_func_verify_device_sig_rs2048() != 39939) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openac_mobile_app_checksum_func_verify_smt_proof() != 34213) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureOpenacMobileAppInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all